steps:
  release-helper:
    image: woodpeckerci/plugin-ready-release-go:3.4.1
    settings:
      git_email: woodpecker-bot@obermui.de
      github_token:
        from_secret: GITHUB_TOKEN

when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}
