when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &golang 'golang:1.24'

steps:
  - name: lint
    image: *golang
    commands:
      - make vet
      - make formatcheck

  - name: test
    image: *golang
    commands:
      - make test
